#!/usr/bin/env node

/**
 * sync-validator-hash — keep the validator bytecode hash pinned in AlgoSafe
 * in sync with the compiled AlgoSafeTxnValidator approval program.
 *
 * Runs after `algokit compile`. Reads the validator's ARC-56 artifact, computes
 * SHA-256 of its compiled approval program, and rewrites
 * `smart_contracts/algo_safe/validator-hash.generated.ts` if it changed.
 * A change means AlgoSafe was compiled against a stale hash, so the compile
 * step is re-run once (the validator's bytecode does not depend on AlgoSafe,
 * so a single re-run always converges).
 */

import { execSync } from 'child_process'
import * as crypto from 'crypto'
import * as fs from 'fs'
import * as path from 'path'

const ROOT_DIR = path.join(__dirname, '..')
const VALIDATOR_ARC56_PATH = path.join(
  ROOT_DIR,
  'smart_contracts',
  'artifacts',
  'algo_safe_validator',
  'AlgoSafeTxnValidator.arc56.json',
)
const GENERATED_PATH = path.join(ROOT_DIR, 'smart_contracts', 'algo_safe', 'validator-hash.generated.ts')

function computeValidatorHash(): string {
  const arc56 = JSON.parse(fs.readFileSync(VALIDATOR_ARC56_PATH, 'utf8')) as {
    byteCode?: { approval?: string }
  }
  const approvalBase64 = arc56.byteCode?.approval
  if (!approvalBase64) {
    throw new Error(`No byteCode.approval in ${VALIDATOR_ARC56_PATH} — compile with bytecode output enabled.`)
  }
  return crypto.createHash('sha256').update(Buffer.from(approvalBase64, 'base64')).digest('hex')
}

function generatedFileContents(hashHex: string): string {
  return [
    '// AUTO-GENERATED by scripts/sync-validator-hash.ts — DO NOT EDIT.',
    '// SHA-256 of the compiled AlgoSafeTxnValidator approval program. The AlgoSafe',
    '// contract pins the validator by this hash at createApplication time.',
    `export const VALIDATOR_APPROVAL_SHA256_HEX = '${hashHex}'`,
    '',
  ].join('\n')
}

function main() {
  const hashHex = computeValidatorHash()
  const contents = generatedFileContents(hashHex)
  const existing = fs.existsSync(GENERATED_PATH) ? fs.readFileSync(GENERATED_PATH, 'utf8') : ''

  if (existing === contents) {
    console.log(`validator-hash: up to date (${hashHex})`)
    return
  }

  fs.writeFileSync(GENERATED_PATH, contents)
  console.log(`validator-hash: updated to ${hashHex} — recompiling contracts against the new pin`)
  execSync('algokit compile ts smart_contracts --output-source-map --out-dir artifacts', {
    cwd: ROOT_DIR,
    stdio: 'inherit',
  })
}

main()
