// AUTO-GENERATED by scripts/sync-validator-hash.ts — DO NOT EDIT.
// SHA-256 of the compiled AlgoSafeTxnValidator approval program. The AlgoSafe
// contract pins the validator by this hash at createApplication time.
export const VALIDATOR_APPROVAL_SHA256_HEX = '0dd692344f80e7d5770f47bcde26c31eaaf24d45b5d177dfcbc7241742e188b1'
