name: Release

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'docs/**'
      - '**.md'
      - '.vscode/**'
      - '.idea/**'

permissions:
  contents: read
  packages: read

jobs:
  algo-safe-contracts-validate:
    name: Run algo-safe-contracts release
    secrets: inherit
    uses: ./.github/workflows/algo-safe-contracts-ci.yaml

  algo-safe-contracts-release:
    name: Run algo-safe-contracts release
    secrets: inherit
    uses: ./.github/workflows/algo-safe-contracts-cd.yaml
    needs: algo-safe-contracts-validate

  algo-safe-frontend-validate:
    name: Run algo-safe-frontend release
    secrets: inherit
    uses: ./.github/workflows/algo-safe-frontend-ci.yaml

  algo-safe-frontend-release:
    name: Run algo-safe-frontend release
    secrets: inherit
    uses: ./.github/workflows/algo-safe-frontend-cd.yaml
    needs: algo-safe-frontend-validate
